/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;


/**
 *
 * @author SENA
 */
public class Agregar_Detalle_Factura extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_Detalle_Factura
     */
    public Agregar_Detalle_Factura() {
        initComponents();
    }

    public JButton getBtnagregar() {
        return btnagregar;
    }

    public void setBtnagregar(JButton btnagregar) {
        this.btnagregar = btnagregar;
    }

    public JButton getBtnbuscar_prod() {
        return btnbuscar_prod;
    }

    public void setBtnbuscar_prod(JButton btnbuscar_prod) {
        this.btnbuscar_prod = btnbuscar_prod;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLbfactura() {
        return lbfactura;
    }

    public void setLbfactura(JLabel lbfactura) {
        this.lbfactura = lbfactura;
    }

    public JLabel getLbnume_fac() {
        return lbnume_fac;
    }

    public void setLbnume_fac(JLabel lbnume_fac) {
        this.lbnume_fac = lbnume_fac;
    }

    public JLabel getLbprodu() {
        return lbprodu;
    }

    public void setLbprodu(JLabel lbprodu) {
        this.lbprodu = lbprodu;
    }

    public JPanel getjPanelagregar_produc() {
        return jPanelagregar_produc;
    }

    public void setjPanelagregar_produc(JPanel jPanelagregar_produc) {
        this.jPanelagregar_produc = jPanelagregar_produc;
    }

   

  

   

    public JTable getTabla_detalle() {
        return tabla_detalle;
    }

    public void setTabla_detalle(JTable tabla_detalle) {
        this.tabla_detalle = tabla_detalle;
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelagregar_produc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_detalle = new javax.swing.JTable();
        lbnume_fac = new javax.swing.JLabel();
        lbprodu = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btnbuscar_prod = new javax.swing.JButton();
        lbfactura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelagregar_produc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Detalle Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 36))); // NOI18N

        tabla_detalle.setBackground(new java.awt.Color(255, 204, 204));
        tabla_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_detalle);

        lbnume_fac.setText("N° Factura");

        lbprodu.setText("Producto");

        btnagregar.setText("Agregar");

        btnbuscar_prod.setText("Buscar;");

        javax.swing.GroupLayout jPanelagregar_producLayout = new javax.swing.GroupLayout(jPanelagregar_produc);
        jPanelagregar_produc.setLayout(jPanelagregar_producLayout);
        jPanelagregar_producLayout.setHorizontalGroup(
            jPanelagregar_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelagregar_producLayout.createSequentialGroup()
                .addGroup(jPanelagregar_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelagregar_producLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelagregar_producLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelagregar_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelagregar_producLayout.createSequentialGroup()
                                .addComponent(lbnume_fac)
                                .addGap(18, 18, 18)
                                .addComponent(lbfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelagregar_producLayout.createSequentialGroup()
                                .addComponent(lbprodu)
                                .addGap(18, 18, 18)
                                .addComponent(btnbuscar_prod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnagregar)
                                .addGap(222, 222, 222)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanelagregar_producLayout.setVerticalGroup(
            jPanelagregar_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelagregar_producLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelagregar_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnume_fac)
                    .addComponent(lbfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelagregar_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelagregar_producLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelagregar_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbprodu)
                            .addComponent(btnbuscar_prod))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelagregar_producLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnagregar)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelagregar_produc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelagregar_produc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar_prod;
    private javax.swing.JPanel jPanelagregar_produc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbfactura;
    private javax.swing.JLabel lbnume_fac;
    private javax.swing.JLabel lbprodu;
    private javax.swing.JTable tabla_detalle;
    // End of variables declaration//GEN-END:variables
}
