/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Buscar_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Buscar_Producto
     */
    public Buscar_Producto() {
        initComponents();
    }

    public JPanel getjPanelbuscar_produc() {
        return jPanelbuscar_produc;
    }

    public void setjPanelbuscar_produc(JPanel jPanelbuscar_produc) {
        this.jPanelbuscar_produc = jPanelbuscar_produc;
    }

    public JTable getTablabuscar_produc() {
        return tablabuscar_produc;
    }

    public void setTablabuscar_produc(JTable tablabuscar_produc) {
        this.tablabuscar_produc = tablabuscar_produc;
    }

    public JTextField getTxtbuscar_produc() {
        return txtbuscar_produc;
    }

    public void setTxtbuscar_produc(JTextField txtbuscar_produc) {
        this.txtbuscar_produc = txtbuscar_produc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelbuscar_produc = new javax.swing.JPanel();
        txtbuscar_produc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablabuscar_produc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelbuscar_produc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 36))); // NOI18N

        txtbuscar_produc.setBackground(new java.awt.Color(204, 204, 255));
        txtbuscar_produc.setText("Buscar;");
        txtbuscar_produc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscar_producActionPerformed(evt);
            }
        });

        tablabuscar_produc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablabuscar_produc);

        javax.swing.GroupLayout jPanelbuscar_producLayout = new javax.swing.GroupLayout(jPanelbuscar_produc);
        jPanelbuscar_produc.setLayout(jPanelbuscar_producLayout);
        jPanelbuscar_producLayout.setHorizontalGroup(
            jPanelbuscar_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbuscar_producLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtbuscar_produc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbuscar_producLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelbuscar_producLayout.setVerticalGroup(
            jPanelbuscar_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbuscar_producLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtbuscar_produc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelbuscar_produc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelbuscar_produc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscar_producActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscar_producActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscar_producActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelbuscar_produc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablabuscar_produc;
    private javax.swing.JTextField txtbuscar_produc;
    // End of variables declaration//GEN-END:variables
}
