/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
    }

    public JLabel getjLbusuarios() {
        return jLbusuarios;
    }

    public void setjLbusuarios(JLabel jLbusuarios) {
        this.jLbusuarios = jLbusuarios;
    }

    public JPanel getjPanelusuario() {
        return jPanelusuario;
    }

    public void setjPanelusuario(JPanel jPanelusuario) {
        this.jPanelusuario = jPanelusuario;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

//    public JLabel getJbltibuscar() {
//        return jbltibuscar;
//    }
//
//    public void setJbltibuscar(JLabel jbltibuscar) {
//        this.jbltibuscar = jbltibuscar;
//    }

    public JTable getTable_buscar_usu() {
        return table_buscar_usu;
    }

    public void setTable_buscar_usu(JTable table_buscar_usu) {
        this.table_buscar_usu = table_buscar_usu;
    }

    public JTextField getTxtbuscar() {
        return txtbuscar;
    }

    public void setTxtbuscar(JTextField txtbuscar) {
        this.txtbuscar = txtbuscar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelusuario = new javax.swing.JPanel();
        jLbusuarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_buscar_usu = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelusuario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelusuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar!!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 36), new java.awt.Color(255, 153, 255))); // NOI18N
        jPanelusuario.setToolTipText("");

        jLbusuarios.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLbusuarios.setText("Usuarios");

        table_buscar_usu.setBackground(new java.awt.Color(255, 204, 204));
        table_buscar_usu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_buscar_usu);

        txtbuscar.setBackground(new java.awt.Color(204, 204, 255));
        txtbuscar.setText("Buscar;");
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelusuarioLayout = new javax.swing.GroupLayout(jPanelusuario);
        jPanelusuario.setLayout(jPanelusuarioLayout);
        jPanelusuarioLayout.setHorizontalGroup(
            jPanelusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelusuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelusuarioLayout.createSequentialGroup()
                        .addComponent(jLbusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanelusuarioLayout.setVerticalGroup(
            jPanelusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelusuarioLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanelusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbusuarios)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelusuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelusuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbusuarios;
    private javax.swing.JPanel jPanelusuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_buscar_usu;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
