/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Buscar_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Buscar_Cliente
     */
    public Buscar_Cliente() {
        initComponents();
    }

    public JPanel getjPanelbuscarClien() {
        return jPanelbuscarClien;
    }

    public void setjPanelbuscarClien(JPanel jPanelbuscarClien) {
        this.jPanelbuscarClien = jPanelbuscarClien;
    }

    public JTable getTable_buscar_cli() {
        return table_buscar_cli;
    }

    public void setTable_buscar_cli(JTable table_buscar_cli) {
        this.table_buscar_cli = table_buscar_cli;
    }

    public JTextField getTxtTable_busCli() {
        return txtTable_busCli;
    }

    public void setTxtTable_busCli(JTextField txtTable_busCli) {
        this.txtTable_busCli = txtTable_busCli;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelbuscarClien = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_buscar_cli = new javax.swing.JTable();
        txtTable_busCli = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelbuscarClien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 36))); // NOI18N

        table_buscar_cli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_buscar_cli);

        txtTable_busCli.setBackground(new java.awt.Color(204, 204, 255));
        txtTable_busCli.setText("Buscar;");

        javax.swing.GroupLayout jPanelbuscarClienLayout = new javax.swing.GroupLayout(jPanelbuscarClien);
        jPanelbuscarClien.setLayout(jPanelbuscarClienLayout);
        jPanelbuscarClienLayout.setHorizontalGroup(
            jPanelbuscarClienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbuscarClienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbuscarClienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTable_busCli, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanelbuscarClienLayout.setVerticalGroup(
            jPanelbuscarClienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbuscarClienLayout.createSequentialGroup()
                .addComponent(txtTable_busCli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelbuscarClien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelbuscarClien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelbuscarClien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_buscar_cli;
    private javax.swing.JTextField txtTable_busCli;
    // End of variables declaration//GEN-END:variables
}
