/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    public JButton getjBttiniciar_seccion() {
        return jBttiniciar_seccion;
    }

    public void setjBttiniciar_seccion(JButton jBttiniciar_seccion) {
        this.jBttiniciar_seccion = jBttiniciar_seccion;
    }

    public JButton getjButtmostrar() {
        return jButtmostrar;
    }

    public void setjButtmostrar(JButton jButtmostrar) {
        this.jButtmostrar = jButtmostrar;
    }

    public JPasswordField getJpcontrasena() {
        return jpcontrasena;
    }

    public void setJpcontrasena(JPasswordField jpcontrasena) {
        this.jpcontrasena = jpcontrasena;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbiniciar_sesion = new javax.swing.JLabel();
        jLbUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLbContrasena = new javax.swing.JLabel();
        jBttiniciar_seccion = new javax.swing.JButton();
        jpcontrasena = new javax.swing.JPasswordField();
        jButtmostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 204));
        jPanel1.setForeground(new java.awt.Color(255, 0, 102));

        jLbiniciar_sesion.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLbiniciar_sesion.setText("Iniciar Sesion ");

        jLbUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbUsuario.setText("Usuario:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jLbContrasena.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbContrasena.setText("Contraseña:");

        jBttiniciar_seccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/persona.png"))); // NOI18N
        jBttiniciar_seccion.setText("Iniciar Sección");
        jBttiniciar_seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttiniciar_seccionActionPerformed(evt);
            }
        });

        jpcontrasena.setToolTipText("");

        jButtmostrar.setText("Mostrar");
        jButtmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtmostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLbContrasena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButtmostrar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLbiniciar_sesion)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLbUsuario)
                                    .addGap(29, 29, 29)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jBttiniciar_seccion)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLbiniciar_sesion)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbUsuario))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbContrasena)
                    .addComponent(jpcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtmostrar))
                .addGap(18, 18, 18)
                .addComponent(jBttiniciar_seccion)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jButtmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtmostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtmostrarActionPerformed

    private void jBttiniciar_seccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttiniciar_seccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBttiniciar_seccionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttiniciar_seccion;
    private javax.swing.JButton jButtmostrar;
    private javax.swing.JLabel jLbContrasena;
    private javax.swing.JLabel jLbUsuario;
    private javax.swing.JLabel jLbiniciar_sesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpcontrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public void setTitle() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
