/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form Venta
     */
    public Venta() {
        initComponents();
    }

    public JTextField getTxtcomprov() {
        return txtcomprov;
    }

    public void setTxtcomprov(JTextField txtcomprov) {
        this.txtcomprov = txtcomprov;
    }

    public JButton getBtnidcli() {
        return btnidcli;
    }

    public void setBtnidcli(JButton btnidcli) {
        this.btnidcli = btnidcli;
    }

    public JButton getBtnidusu() {
        return btnidusu;
    }

    public void setBtnidusu(JButton btnidusu) {
        this.btnidusu = btnidusu;
    }

    public JButton getBut_guardarv() {
        return But_guardarv;
    }

    public void setBut_guardarv(JButton But_guardarv) {
        this.But_guardarv = But_guardarv;
    }

    public JComboBox<String> getCombtipov() {
        return Combtipov;
    }

    public void setCombtipov(JComboBox<String> Combtipov) {
        this.Combtipov = Combtipov;
    }

    public JPanel getPanelventa() {
        return Panelventa;
    }

    public void setPanelventa(JPanel Panelventa) {
        this.Panelventa = Panelventa;
    }

    public JLabel getLbtitu_venta() {
        return lbtitu_venta;
    }

    public void setLbtitu_venta(JLabel lbtitu_venta) {
        this.lbtitu_venta = lbtitu_venta;
    }

    public JTextField getTxtclienv() {
        return txtclienv;
    }

    public void setTxtclienv(JTextField txtclienv) {
        this.txtclienv = txtclienv;
    }

    public JTextField getTxtidusuv() {
        return txtidusuv;
    }

    public void setTxtidusuv(JTextField txtidusuv) {
        this.txtidusuv = txtidusuv;
    }

    public JTextField getTxtidventa() {
        return txtidventa;
    }

    public void setTxtidventa(JTextField txtidventa) {
        this.txtidventa = txtidventa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelventa = new javax.swing.JPanel();
        lbtitu_venta = new javax.swing.JLabel();
        lbideventa = new javax.swing.JLabel();
        lbideclienv = new javax.swing.JLabel();
        lbidusuv = new javax.swing.JLabel();
        lbtipopagov = new javax.swing.JLabel();
        txtidventa = new javax.swing.JTextField();
        txtclienv = new javax.swing.JTextField();
        txtidusuv = new javax.swing.JTextField();
        Combtipov = new javax.swing.JComboBox<>();
        But_guardarv = new javax.swing.JButton();
        btnidcli = new javax.swing.JButton();
        btnidusu = new javax.swing.JButton();
        lbcomprova = new javax.swing.JLabel();
        txtcomprov = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbtitu_venta.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbtitu_venta.setText("Nueva Venta");

        lbideventa.setText("Iendificacion De Ventas");

        lbideclienv.setText("Identificacion Del Cliente");

        lbidusuv.setText("Identificacion Del Usuarios");

        lbtipopagov.setText("Tipo De Pago ");

        Combtipov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Tarjeta de Credito", "Tarjeta de Débito", "Efectivo", "PSE" }));

        But_guardarv.setText("Guardar ");

        btnidcli.setText("buscar clientes");
        btnidcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidcliActionPerformed(evt);
            }
        });

        btnidusu.setText("buscar usuarios");

        lbcomprova.setText("N° Comprovante");

        javax.swing.GroupLayout PanelventaLayout = new javax.swing.GroupLayout(Panelventa);
        Panelventa.setLayout(PanelventaLayout);
        PanelventaLayout.setHorizontalGroup(
            PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelventaLayout.createSequentialGroup()
                .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelventaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbideventa)
                            .addComponent(lbidusuv)
                            .addComponent(lbideclienv)
                            .addGroup(PanelventaLayout.createSequentialGroup()
                                .addComponent(lbtipopagov)
                                .addGap(17, 17, 17)))
                        .addGap(96, 96, 96)
                        .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelventaLayout.createSequentialGroup()
                                .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidventa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelventaLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(Combtipov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelventaLayout.createSequentialGroup()
                                .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtidusuv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(txtclienv, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcomprov, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnidcli, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnidusu, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(PanelventaLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lbtitu_venta)))
                .addGap(26, 26, 26))
            .addGroup(PanelventaLayout.createSequentialGroup()
                .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelventaLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(But_guardarv))
                    .addGroup(PanelventaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbcomprova)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelventaLayout.setVerticalGroup(
            PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelventaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbtitu_venta)
                .addGap(31, 31, 31)
                .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtidventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbideventa))
                .addGap(35, 35, 35)
                .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbideclienv)
                    .addComponent(txtclienv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnidcli))
                .addGap(32, 32, 32)
                .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbidusuv)
                    .addComponent(txtidusuv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnidusu))
                .addGap(18, 18, 18)
                .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbcomprova)
                    .addComponent(txtcomprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(PanelventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtipopagov)
                    .addComponent(Combtipov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(But_guardarv)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panelventa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panelventa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnidcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnidcliActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton But_guardarv;
    private javax.swing.JComboBox<String> Combtipov;
    private javax.swing.JPanel Panelventa;
    private javax.swing.JButton btnidcli;
    private javax.swing.JButton btnidusu;
    private javax.swing.JLabel lbcomprova;
    private javax.swing.JLabel lbideclienv;
    private javax.swing.JLabel lbideventa;
    private javax.swing.JLabel lbidusuv;
    private javax.swing.JLabel lbtipopagov;
    private javax.swing.JLabel lbtitu_venta;
    private javax.swing.JTextField txtclienv;
    private javax.swing.JTextField txtcomprov;
    private javax.swing.JTextField txtidusuv;
    private javax.swing.JTextField txtidventa;
    // End of variables declaration//GEN-END:variables
}
